---
title: "Survey package"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rje) #for expit
library(survival)
library(survey)
```
# the simulation function
Get the exposure and bv not correlated to see the outcomes.
```{r simulation}
bv.simulation.2 <- function(exp.rate, beta, gamma, baseline.hazards, epsilon) {
# exp.rate is the exposure rate to HIV
# beta is the coefficient (intercept) in generating BV status
# gamma is the coefficient in generate BV status, and varied to control association
# of HIV exposure and BV status
  ########### main body #############
# generate sites and participants, sites 1:10, participants per site 1:250
sites <- rep(1:10, each = 250)
participants <- 1:2500
# generate exposure rates for study sites
# a.set <- seq(exp.rate-0.16,exp.rate+0.20, 0.04)
# calculate hiv exposure for each site
HIV.exp <- rbinom(2500,1,exp.rate) # varying by site as the original simulation plan
# generate bv status
bv <- rbinom(2500,1,expit(beta + gamma*HIV.exp))# correlation with HIV exp varies, increase gamma and cut beta
# generate the intervention assignment
# tx <- rep(c(0,1),times = 125)
# generate the hazards
# overall HIV incidence of 5% per year
individual.hazards <- baseline.hazards*exp(epsilon*bv) # only epsilon
# set those whose exposure status of 0 to small hazard
individual.hazards.2 <- ifelse(HIV.exp==0, 0.00001, individual.hazards)
Time.to.HIV <- rexp(2500, individual.hazards.2)
# combine and arrange the time to hiv
sort.time <- sort(Time.to.HIV)
sort.time[160]
# add numbering to the dataset
# set the time to event to NA if  exceed 160 events (study ends when reach 160 events)
Time.to.HIV <- ifelse(Time.to.HIV <= sort.time[160], Time.to.HIV, sort.time[160]+1)
# identify those top 160 time to events and label them with HIV infection
HIV.infection <- ifelse(Time.to.HIV <= sort.time[160], 1, 0)
data.frame(sites,participants,HIV.exp,bv,individual.hazards.2,Time.to.HIV,HIV.infection)
} # wait until the end to combine the data
# test the function
bv.sim.2 <- bv.simulation.2(0.4, -1.5, 2.5, 0.0001405205, 0)

bv.sim.2 %>% summarise(prop = mean(bv)) %>%
                    .$prop  # should be close to 40%
bv.sim.2 %>% summarise(prop = mean(HIV.exp)) %>%
                    .$prop # should be close to 40%
```
# Implementing the survey package: Lin & Ying
```{r}
# simple random
rep.svy.LY <- function(hiv.exp, beta, gamma) {
bv.sim.2 <- bv.simulation.2(hiv.exp, beta, gamma, 0.0001405205, 0)

sel.sub <- sample(bv.sim.2$participants,250,replace = F)
bv.sim.2$sel.sub <- ifelse(bv.sim.2$participants %in% sel.sub, 1, 0)

dcch<-twophase(id=list(~participants,~participants), strata=list(NULL,~HIV.infection),
                  subset=~I(sel.sub | HIV.infection), data=bv.sim.2)
fit1 <- svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=dcch)
# probabilities
rates <- rep(0,10)
  for (i in 1:10) {
  rates[i] <- bv.sim.2 %>% filter(sites == i) %>%
  summarise(prop = mean(HIV.infection)) %>%
                    .$prop
  }
  HIV.probs.list <- rep(rates, each = 250)# tabulate
  indexes.proportion <- sample(bv.sim.2$participants, size = 250, prob = HIV.probs.list, replace =   FALSE)
  bv.sim.2$site.sel.proportion <- ifelse(bv.sim.2$participants %in% indexes.proportion, 1, 0)

dcch.site1<-twophase(id=list(~participants,~participants), strata=list(NULL,~HIV.infection),
                  subset=~I(site.sel.proportion | HIV.infection), data=bv.sim.2)
fit2 <- svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=dcch.site1)
# logistic
  logit1 <- glm(HIV.infection~as.factor(sites), data=bv.sim.2, family = "binomial")
  ## use the original method posted in the MORGAM paper to get the probability of getting infection
  bv.sim.2$Site.prob <- predict(logit1, newdata = bv.sim.2, type = "response")
  indexes.logit <- sample(bv.sim.2$participants, size = 250, prob = bv.sim.2$Site.prob[1:2500], replace = FALSE)
  # generating the dataset
  bv.sim.2$site.sel.logit <- ifelse(bv.sim.2$participants %in% indexes.logit, 1, 0)
dcch.site2<-twophase(id=list(~participants,~participants), strata=list(NULL,~HIV.infection),
                  subset=~I(site.sel.logit | HIV.infection), data=bv.sim.2)
fit3 <- svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=dcch.site2)
matrix(c(fit1$coefficients,fit1$var,
         fit2$coefficients,fit2$var,
         fit3$coefficients,fit3$var), byrow = TRUE)
}
mat1 <- replicate(1000,rep.svy.LY(0.4, -1.5, 2.5))

convert_to_table <- function(dataset,n) {
first.set <- matrix(dataset, nrow = n, byrow = TRUE)
result1.mean <- apply(first.set, 2, mean)
table1 <- matrix(result1.mean, nrow = 3, byrow = TRUE)
colnames(table1) <- c("mean","variance")
rownames(table1) <- c("SRS","Baseline-adjusted 1","Baseline-adjusted 2")
table1
}

```
# Implementing the stratified design (Borgan)
```{r}

rep.svy.Borgan <- function(hiv.exp, beta, gamma) {
bv.sim.2 <- bv.simulation.2(hiv.exp, beta, gamma, 0.0001405205, 0)

sel.sub <- sample(bv.sim.2$participants,250,replace = F)
bv.sim.2$sel.sub <- ifelse(bv.sim.2$participants %in% sel.sub, 1, 0)

d_BorganII <- twophase(id=list(~participants,~participants), strata=list(NULL,~interaction(sites,HIV.infection)),
                  subset=~I(sel.sub | HIV.infection), data=bv.sim.2)
b1 <-svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=d_BorganII)
# probabilities
rates <- rep(0,10)
  for (i in 1:10) {
  rates[i] <- bv.sim.2 %>% filter(sites == i) %>%
  summarise(prop = mean(HIV.infection)) %>%
                    .$prop
  }
  HIV.probs.list <- rep(rates, each = 250)# tabulate
  indexes.proportion <- sample(bv.sim.2$participants, size = 250, prob = HIV.probs.list, replace =   FALSE)
  bv.sim.2$site.sel.proportion <- ifelse(bv.sim.2$participants %in% indexes.proportion, 1, 0)

borgan.site1<-twophase(id=list(~participants,~participants), strata=list(NULL,~interaction(sites,HIV.infection)),
                  subset=~I(site.sel.proportion | HIV.infection), data=bv.sim.2)
b2 <- svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=borgan.site1)

# logistic
  logit1 <- glm(HIV.infection~as.factor(sites), data=bv.sim.2, family = "binomial")
  ## use the original method posted in the MORGAM paper to get the probability of getting infection
  bv.sim.2$Site.prob <- predict(logit1, newdata = bv.sim.2, type = "response")
  indexes.logit <- sample(bv.sim.2$participants, size = 250, prob = bv.sim.2$Site.prob[1:2500], replace = FALSE)
  # generating the dataset
  bv.sim.2$site.sel.logit <- ifelse(bv.sim.2$participants %in% indexes.logit, 1, 0)

borgan.site2<-twophase(id=list(~participants,~participants), strata=list(NULL,~interaction(sites,HIV.infection)),
                  subset=~I(site.sel.logit | HIV.infection), data=bv.sim.2)
b3 <- svycoxph(Surv(Time.to.HIV,HIV.infection)~bv+strata(sites),
                design=borgan.site2)
matrix(c(b1$coefficients,b1$var,
         b2$coefficients,b2$var,
         b3$coefficients,b3$var), byrow = TRUE)
}

mat2 <- replicate(1000,rep.svy.Borgan(0.4, -1.5, 2.5))
second.set <- matrix(mat2, nrow = 1000, byrow = TRUE)
result2.mean <- apply(second.set, 2, mean)


```

# Result summary
```{r}
exp.rate <- 0.2
beta <- 0
gamma <- 6.0
HIV.exp <- rbinom(2500,1,exp.rate)
bv <- rbinom(2500,1,expit(beta + gamma*HIV.exp))
mean(bv)

# 40% HIV, 40% BV, beta = -1.5, gamma = 2.5
(LY.40.40 <- convert_to_table(mat1, 1000))
(B.40.40 <- convert_to_table(mat2, 1000))
# 20% HIV, 20% BV, beta = -1.9, gamma = 2.0
mat1.20.20 <- replicate(1000,rep.svy.LY(0.2, -1.9, 2.0))
mat2.20.20 <- replicate(1000,rep.svy.Borgan(0.2, -1.9, 2.0))
(LY.20.20 <- convert_to_table(mat1.20.20, 1000))
(B.20.20 <- convert_to_table(mat2.20.20, 1000))
# 60% HIV, 60% BV, beta = -1.5, gamma = 3.5
mat1.60.60 <- replicate(1000,rep.svy.LY(0.6, -1.5, 3.5))
mat2.60.60 <- replicate(1000,rep.svy.Borgan(0.6, -1.5, 3.5))
(LY.60.60 <- convert_to_table(mat1.60.60, 1000))
(B.60.60 <- convert_to_table(mat2.60.60, 1000))
# 60% HIV, 20% BV, beta = -1.7, gamma = 0.5
mat1.60.20 <- replicate(1000,rep.svy.LY(0.6, -1.7, 0.5))
mat2.60.20 <- replicate(1000,rep.svy.Borgan(0.6, -1.7, 0.5))
(LY.60.20 <- convert_to_table(mat1.60.20, 1000))
(B.60.20 <- convert_to_table(mat2.60.20, 1000))
# 20% HIV, 60% BV, beta = 0, gamma = 6.0
mat1.20.60 <- replicate(1000,rep.svy.LY(0.2, 0, 6.0))
mat2.20.60 <- replicate(1000,rep.svy.Borgan(0.2, 0, 6.0))
(LY.20.60 <- convert_to_table(mat1.20.60, 1000))
(B.20.60 <- convert_to_table(mat2.20.60, 1000))

```